name: Tests
on: push
jobs:
  smoke:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Prepare venv
        run: make init
      - name: Prepare folder
        run: mkdir downloads
      - name: Test
        run: |
          make run &
          sleep 5
          curl http://localhost:5000 | grep "Simple Downloader"
  docker_build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Test
        run: make docker-build
