name: Tests
on: push
jobs:
  smoke:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@v1
#      - name: Run chromedriver
#        run: |
#          export DISPLAY=:99
#          chromedriver --url-base=/wd/hub &
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Prepare npm
        run: |
          cd frontend/src
          npm install
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Prepare venv
        run: make init
      - name: Create test file
        run: |
          mkdir downloads
          touch downloads/test-file
      - name: Test
        run: |
          make run-frontend &
          make run-backend &
          sleep 20
          make test-downloaded-file
  docker_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Test
        run: make docker-build
